"""replace summary with research_data

Revision ID: 0f25987d72eb
Revises: b9cebf56945b
Create Date: 2026-06-04 23:03:20.829798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f25987d72eb'
down_revision: Union[str, Sequence[str], None] = 'b9cebf56945b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_sessions', sa.Column('research_data', sa.JSON(), nullable=False))
    op.drop_column('research_sessions', 'summary')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_sessions', sa.Column('summary', sa.VARCHAR(length=5000), autoincrement=False, nullable=False))
    op.drop_column('research_sessions', 'research_data')
    # ### end Alembic commands ###
