"""add progress message

Revision ID: 640ff30788fb
Revises: 94f4e395be2d
Create Date: 2026-06-08 01:38:21.594323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '640ff30788fb'
down_revision: Union[str, Sequence[str], None] = '94f4e395be2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_sessions', sa.Column('progress_message', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_sessions', 'progress_message')
    # ### end Alembic commands ###
