"""add research status

Revision ID: 94f4e395be2d
Revises: 0f25987d72eb
Create Date: 2026-06-07 17:55:47.458089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94f4e395be2d'
down_revision: Union[str, Sequence[str], None] = '0f25987d72eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_sessions', sa.Column('status', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_sessions', 'status')
    # ### end Alembic commands ###
